src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Budget_Type__c</fullName>
        <label>Budget Type</label>
        <picklist>
            <picklistValues>
                <fullName>Furniture</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Books</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prof Event Participation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ViewRequestControllerTest.cls
@isTest
private class ViewRequestControllerTest {

    private static ViewRequestController viewRequestController;

    private static void init() {
        Request__c request = new Request__c(Name = '111', Subject__c = '222', Budget_Type__c = 'Vacancy');
        insert request;
        PageReference pr = Page.ViewRequest;
        pr.getParameters().put('Id', request.Id);
        Test.setCurrentPageReference(pr);
        viewRequestController = new ViewRequestController();
    }

    @isTest static void testAccept_Fail() {  
        init();
        viewRequestController.madeVacancy.HR_Manager__c = null;
        viewRequestController.doAccept();
        System.assertNotEquals(viewRequestController.errorMsg, null);
    }
    
    @isTest static void testReject_Fail() {
        init();
        viewRequestController.doReject();
        System.assertNotEquals(viewRequestController.gottenRequest, null);
    }

    @isTest static void testInit_Fail() {
        init();
        viewRequestController = new ViewRequestController();
        try {
            viewRequestController.init();
        }
        catch(System.QueryException exc) {

        }
        System.assertNotEquals(viewRequestController, null);
    }
    
}