src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vacancy__c.object
<CustomObject>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Vacancy</label>
    <nameField>
        <label>Vacancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <recordTypes>
        <fullName>Request</fullName>
        <active>true</active>
        <label>Request record type</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RequestEmailHandler.cls
public class RequestEmailHandler {

	public static void sendEmail() {

		EmailTemplate et = [SELECT ID, Subject, HtmlValue, Body 
		                    FROM EmailTemplate 
		                    WHERE Name =:'Employee request'];

		Profile pr = [ SELECT ID 
		           	   FROM Profile
		           	   WHERE Name = 'General Manager (GM)' 
		           	   LIMIT 1];

		User gm = [SELECT ID, Name
		           FROM User 
		           WHERE ProfileId =: pr.Id
		           LIMIT 1];

		Request__c rst = [SELECT ID, Job_Title__c FROM Request__c LIMIT 1];

        String subject = et.Subject;
		String htmlBody = et.HtmlValue;
		htmlBody = htmlBody.replace('{!User.Name}', gm.Name);
		htmlBody = htmlBody.replace('{!Vacancy__c.Id}', rst.Id);
		htmlBody = htmlBody.replace('{!Post}', rst.Job_Title__c + ' ');
		htmlBody = htmlBody.replace(']]>', '');

		Messaging.SingleEmailMessage message = 
		              new Messaging.SingleEmailMessage();

        message.setTargetObjectId(gm.Id);
        message.setSubject(subject);
        message.setHtmlBody(htmlBody);
        message.saveAsActivity = false;

        List<Messaging.SingleEmailMessage> emails = 
	            new List<Messaging.SingleEmailMessage>();

	    emails.add(message);

	    Messaging.sendEmail(emails); 

	}

}