src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Budget_Type__c</fullName>
        <label>Budget Type</label>
        <picklist>
            <picklistValues>
                <fullName>Furniture</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Books</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prof Event Participation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certification</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Waiting for approval</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RequestSkill__c.object
<CustomObject>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>RequestSkills</relationshipLabel>
        <relationshipName>RequestSkills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skill__c</referenceTo>
        <relationshipLabel>RequestSkills</relationshipLabel>
        <relationshipName>RequestSkills</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RequestSkill</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>RequestSkill</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RequestSkills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Skill__c.object
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vacancy__c.object
<CustomObject>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Vacancy</label>
    <nameField>
        <label>Vacancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vacancies</pluralLabel>
    <recordTypes>
        <fullName>Request</fullName>
        <active>true</active>
        <label>Request record type</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vacancy</fullName>
        <active>true</active>
        <label>Vacancy record type</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ViewRequestController.cls
public with sharing class ViewRequestController {

    public Request__c gottenRequest {get; set;}
    public Vacancy__c madeVacancy {get; set;}
    public List<Skill__c> neededSkills {get; set;}    

    public void init() {
         gottenRequest = [SELECT Subject__c, CreatedById, Budget_Type__c
                        FROM Request__c
                        WHERE ID =: ApexPages.currentPage().getParameters().get('Id')
                        LIMIT 1];
        if(gottenRequest.Budget_Type__c.equals('Vacancy')) {
            madeVacancy = new Vacancy__c();
            neededSkills = [SELECT Name
                            FROM Skill__c
                            WHERE ID IN (SELECT Skill__c FROM RequestSkill__c WHERE Request__c =: gottenRequest.ID)
                            LIMIT 1000];
        }
    }

    public ViewRequestController() {

    }   

    public PageReference accept() {
        if(gottenRequest == null) {
            init();
        }
        try {
            if(gottenRequest.Budget_Type__c.equals('Vacancy')) {
                gottenRequest.Request_Status__c = 'Accepted';
                update gottenRequest;
                madeVacancy.Active__c = true;
                madeVacancy.Job_Title__c = gottenRequest.Subject__c;
                insert madeVacancy;
                EmailTemplate emailTemplate = [SELECT Id, HtmlValue FROM EmailTemplate WHERE Name = 'Accepted Vacancy Request'];        
                EmailHandler.sendApprovedRequestEmail(emailTemplate, gottenRequest, madeVacancy.ID, new String[] {
                    '{!vacancyLink}', 
                    'New Vacancy'
                    });
                return new PageReference('http://ap2.salesforce.com/' + madeVacancy.ID);
            }
        }
        catch(System.EmailException exc) {
                return null;
        }
        return null;
    }

    public PageReference reject() {
        if(gottenRequest == null) {
            init();
        }
        try {
            gottenRequest.Request_Status__c = 'Rejected';
            EmailTemplate emailTemplate = [SELECT Id, HtmlValue FROM EmailTemplate WHERE Name = 'Rejected Request'];        
            EmailHandler.sendRejectedRequestEmail(emailTemplate, gottenRequest);
            update gottenRequest;
            return new PageReference('http://ap2.salesforce.com/' + gottenRequest.ID);
        }
        catch(System.EmailException exc) {
            return null;
        }
    }
}